cardPaymentMethodSpecificInput:
    isRecurring: %recurring%
    recurringPaymentSequenceIndicator: %installment%
    token: %recurring_payment_token%
order:
    amountOfMoney:
        amount: %amount%
        currencyCode: %currency%
    references:
        descriptior: %descriptor%
        merchantReference: %order_id%
