<?php

namespace SmashPig\PaymentProviders\Chariot\Audit;

use SmashPig\Core\DataFiles\AuditParser;
use SmashPig\Core\UtcDate;

// Parser for Chariot donations audit CSV files generated by
// PaymentProviders/Chariot/Maintenance/GetReport.php.
class DonationsAudit implements AuditParser {

	public function parseFile( string $path ): array {
		$handle = fopen( $path, 'r' );
		if ( !$handle ) {
			throw new \RuntimeException( 'Unable to open file ' . $path );
		}

		$headers = fgetcsv( $handle );
		if ( !$headers ) {
			fclose( $handle );
			return [];
		}

		$output = [];
		while ( ( $row = fgetcsv( $handle ) ) !== false ) {
			if ( count( $row ) === 1 && trim( (string)$row[0] ) === '' ) {
				continue;
			}
			$combined = [];
			foreach ( $headers as $index => $header ) {
				$combined[$header] = $row[$index] ?? '';
			}
			$output[] = $this->normalizeRow( $combined );
		}

		fclose( $handle );
		return $output;
	}

	private function normalizeRow( array $row ): array {
		$msg = [
			'gateway' => 'chariot',
			'audit_file_gateway' => 'chariot',
			'type' => $row['type'] ?: 'donation',
			'date' => $this->toUtcTimestamp( $row['date'] ?? null ),
			'order_id' => $this->firstNonEmpty( $row['order_id'] ?? null, $row['platform_grant_id'] ?? null, $row['gateway_txn_id'] ?? null ),
			'gateway_txn_id' => $row['gateway_txn_id'] ?: null,
			'backend_processor_txn_id' => $this->firstNonEmpty( $row['backend_processor_txn_id'] ?? null, $row['payment_source_id'] ?? null ),
			'currency' => $row['currency'] ?: null,
			'gross' => $row['gross'] ?: null,
			'original_total_amount' => $row['original_total_amount'] ?: null,
			'original_currency' => $row['original_currency'] ?: null,
			'settled_total_amount' => $row['settled_total_amount'] ?: null,
			'settled_fee_amount' => $row['settled_fee_amount'] ?: null,
			'settled_net_amount' => $row['settled_net_amount'] ?: null,
			'settled_currency' => $row['settled_currency'] ?: null,
			'settled_date' => $this->toUtcTimestamp( $row['settled_date'] ?? null ),
			'settlement_batch_reference' => $row['settlement_batch_reference'] ?: null,
			'donor_name' => $row['donor_name'] ?: null,
			'donor_first_name' => $row['donor_first_name'] ?: null,
			'donor_last_name' => $row['donor_last_name'] ?: null,
			'donor_email' => $row['donor_email'] ?: null,
			'donor_phone' => $row['donor_phone'] ?: null,
			'donor_fund_name' => $row['donor_fund_name'] ?: null,
			'purpose' => $row['purpose'] ?: null,
			'note' => $row['note'] ?: null,
			'match_amount' => $row['match_amount'] ?: null,
			'platform_fee_amount' => $row['platform_fee_amount'] ?: null,
			'platform_name' => $row['platform_name'] ?: null,
			'platform_grant_id' => $row['platform_grant_id'] ?: null,
			'daf_organization' => $row['daf_organization'] ?: null,
			'daf_program' => $row['daf_program'] ?: null,
			'donor_address_street' => $row['donor_address_street'] ?: null,
			'donor_address_street_2' => $row['donor_address_street_2'] ?: null,
			'donor_address_city' => $row['donor_address_city'] ?: null,
			'donor_address_state' => $row['donor_address_state'] ?: null,
			'donor_address_postal_code' => $row['donor_address_postal_code'] ?: null,
			'donor_address_country' => $row['donor_address_country'] ?: null,
		];

		return array_filter( $msg, static fn ( $value ) => $value !== null && $value !== '' );
	}

	private function firstNonEmpty( ?string ...$values ): ?string {
		foreach ( $values as $value ) {
			if ( $value !== null && trim( $value ) !== '' ) {
				return $value;
			}
		}
		return null;
	}

	private function toUtcTimestamp( ?string $value ): ?int {
		if ( $value === null || trim( $value ) === '' ) {
			return null;
		}
		return UtcDate::getUtcTimestamp( $value );
	}
}
