# Settings for Braintree (owned by PayPal)
#
# To override, create a file in:
#   /etc/smashpig/braintree/main.yaml
#   $HOME/.smashpig/braintree/main.yaml

api:
    class: SmashPig\PaymentProviders\Braintree\Api
    constructor-parameters:
        -
            merchant-id: 16charalphanumer
            public-key: 16charalphanumer
            private-key: 32characterlongalphanumericstrng
            endpoint: https://payments.braintree-api.com/graphql
            version: '2022-03-07'
            # Date in the format YYYY-MM-DD. We recommend using the date on which you begin integrating with the GraphQL API.
            # Needs to be quoted for YAML reasons.

payment-provider:
    test:
        class: SmashPig\PaymentProviders\Braintree\TestPaymentProvider
